version: '3.1'

services:
  frontend:
    image: cyb-frontend
    restart: always
    ports:
      - 3333:3000
    environment:
      BACKEND_API_ENDPOINT: http://backend:5000/lists

  backend:
    image: cyb-backend
    restart: always
    environment:
      MONGODB_CONNECTION_STRING: mongodb://root:example@mongo:27017/

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
